# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
 workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 name: Environment-based Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        options: ['DEV', 'QA', 'PROD']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Run actions based on the selected environment
      - name: Run actions based on environment
        run: |
          case "${{ github.event.inputs.environment }}" in
            DEV)
              echo "Running actions for DEV environment"
              # Add your actions specific to DEV environment
              ;;
            QA)
              echo "Running actions for QA environment"
              # Add your actions specific to QA environment
              ;;
            PROD)
              echo "Running actions for PROD environment"
              # Add your actions specific to PROD environment
              ;;
          esac

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   # - name: Setup .NET
    #  uses: actions/setup-dotnet@v3
    #  with:
      #  dotnet-version:  4.7.2
   # - name: Restore dependencies
    #  run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
   # - name: Test
   #   run: dotnet test --no-build --verbosity normal
